[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["cdylib", "rlib"]

[dependencies]
getrandom = { version = "0.2.9", features = ["js"] }
rand = "0.8.5"
wasm-bindgen = "0.2.80"
